name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 12

      - name: Node v24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: src-tauri

      - name: install dependencies
        run: pnpm install

      - name: install Tauri dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          webkit2gtk-4.1
          libayatana-appindicator3-dev
          webkit2gtk-driver
          xvfb

      - name: install msdgedriver (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cargo install --git https://github.com/chippers/msedgedriver-tool
          & "$HOME/.cargo/bin/msedgedriver-tool.exe"
          $PWD.Path >> $env:GITHUB_PATH

      - name: run e2e tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pnpm install
          xvfb-run pnpm test
        working-directory: e2e

      - name: run e2e tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          winget install gerardog.gsudo --accept-source-agreements --accept-package-agreements
          icacls "$env:GITHUB_WORKSPACE" /setintegritylevel "(OI)(CI)Fm" /T
          pnpm install
          sudo --integrity Medium pnpm test
        working-directory: e2e

      - name: run e2e tests (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pnpm install
          pnpm test
        working-directory: e2e
        env:
          CN_API_KEY: ${{ secrets.CN_API_KEY }}
